RutubeVideoCollector:
  max_videos_per_category: 200
  max_videos_per_tag: 300
  min_duration: 3
  max_duration: 33
  quality: 'worst'
  audio_fps: 16000
  n_frames: 64
  frame_dimensions: (256, 256)


TrainParam:
 task: "txt2tag" # txt2tag
 use_device: "cuda" # cuda, cpu
 start_learning_rate: 0.00001
 name_models: ['keyT5_tags_custom']
 pretrained_weight_bert_class: 'ai-forever/ruBert-base'
 pretrained_weight_tag: 'emelnov/keyT5_tags_custom' # '0x7o/keyt5-base', '0x7o/keyt5-large', 'emelnov/keyT5_tags_custom'
 use_text_lematization: False
 use_text_augmentation: True
 use_fast_tokenizer: True
 clean_up_tokenization_spaces: True
 use_random_token_mask: True
 list_no_include_cat: None # ['Обзоры и распаковки товаров', 'Лайфстайл', 'Недвижимость', 'Здоровье', 'Природа', 'Дизайн', 'Техника и оборудование', 'Бизнес и предпринимательство', 'Культура', 'Религия', 'Строительство и ремонт', 'Сад и огород', 'Аудиокниги', 'Еда', 'Интервью', 'Развлечения', 'Лайфхаки', 'Эзотерика', 'Охота и рыбалка', 'Наука', 'Политика', 'Психология', 'Аудио', 'Технологии и интернет', 'Красота', 'Телепередачи', 'Детям', 'Аниме', 'Хобби', 'Видеоигры', 'Юмор', 'Обучение', 'Спорт', 'Разное', 'Путешествия', 'Животные', 'Новости и СМИ', 'Мультфильмы', 'Музыка', 'Сериалы', 'Фильмы', 'Авто-мото']
 max_title_length: 1024
 max_description_length: 4096
 max_tag_length: 1024
 max_length_generation: 64
 early_stopping: True
 num_beams: 5
 num_classes: 42 # count category
 batch_size: 1
 num_workers: 0 # bug then more 0
 pin_memory: True # turn off with cpu
 image_size: 64
 sample_duration: 64 # num frame for train
 n_channels: 3
 num_epochs: 10
 embedding_dim: 512 # size feature
 tag_similarity: 0.8
 name_optimizer: "Adam" # SGD, Adam
 val_size: 0.1
 test_size: 0.1
 seed: 17