RutubeVideoCollector:
  max_videos_per_category: 200
  max_videos_per_tag: 300
  min_duration: 3
  max_duration: 33
  quality: 'worst'
  audio_fps: 16000
  n_frames: 64
  frame_dimensions: (256, 256)


EmbeddingCollector:
  batch_size: 8
  image_size: 256
  image_model_path: 'microsoft/LLM2CLIP-Openai-B-16' # from huggingface
  clip_image_processor: 'openai/clip-vit-base-patch16'
  text_model_path: 'BAAI/bge-m3' # from FlagEmbedding
  sample_rate: 16000
  audio_model_path: 'openai/whisper-large-v3-turbo' # from huggingface


GraphNodeCollector:
  similarity_threshold: 0.65


ClusterCollector:
  task: "cluster"
  loky_max_cpu_count: 8


TrainParamEmbed2Tag:
 use_device: "cuda" # cuda, cpu
 pretrained_weight_tag: "emelnov/keyT5_tags_custom"
 name_model: 'Embed2TagV1'
 early_stopping: True
 num_beams: 3
 concat_embed_dim: 3840
 max_length_generation: 15
 tag_similarity: 0.7
 start_learning_rate: 0.00001
 batch_size: 2
 num_workers: 0
 num_epochs: 1
 pin_memory: False
 name_optimizer: "Adam" # SGD, Adam
 val_size: 0.2
 test_size: 0.2
 seed: 17


TrainParamEmbed2CatSubcat:
  use_device: "cuda" # cuda, cpu
  start_learning_rate: 0.00001
  name_model: 'Embed2CatSubcatv2'
  num_classes: 43
  num_subclasses: 1024
  list_no_include_cat: None
  list_no_include_sub: None
  batch_size: 10
  num_workers: 0 # bug then more 0
  pin_memory: False # turn off with cpu
  num_epochs: 20
  name_optimizer: "Adam" # SGD, Adam
  val_size: 0.05
  test_size: 0.05
  seed: 17


MetricsVisualizer:
  part_sub: 13
  task: "embed2tag" # embed2tag  # embed2catsubcat
